# GitHub Secrets 內的變數清單：
# DB_USERNAME - 資料庫用戶名
# DB_PASSWORD - 資料庫密碼
# AWS_ACCESS_KEY - AWS 存取密鑰
# AWS_SECRET_KEY - AWS 秘密密鑰
# SPRING_MAIL_USERNAME - 郵件服務用戶名
# SPRING_MAIL_PASSWORD - 郵件服務密碼
# SERVER_SSL_KEY_STORE_PASSWORD - SSL Key Store 密碼
# AWS_S3_BUCKET_NAME - AWS S3 儲存桶名稱
# AWS_REGION - AWS 區域
# EC2_PUBLIC_IP - EC2 伺服器的公有 IP 地址
# EC2_SSH_KEY - EC2 SSH 密鑰


name: CI/CD for Maven Project with Docker

on:
  push:
    branches:
      - main  # 當推送到分支時觸發工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 作為運行環境

    env:  # 定義全局環境變數
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
      SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
      SERVER_SSL_KEY_STORE_PASSWORD: ${{ secrets.SERVER_SSL_KEY_STORE_PASSWORD }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

    steps:
      - name: Checkout code  # 檢出代碼
        uses: actions/checkout@v2

      - name: Set up JDK 17  # 設置 Java 環境
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Test with Maven  # 使用 Maven 構建應用並運行測試
        run: mvn clean package
        env:
          SPRING_DATASOURCE_URL: ${{ env.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ env.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ env.SPRING_DATASOURCE_PASSWORD }}
          SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ env.SPRING_JPA_HIBERNATE_DDL_AUTO }}
          SPRING_JPA_DATABASE_PLATFORM: ${{ env.SPRING_JPA_DATABASE_PLATFORM }}
          SPRING_MAIL_USERNAME: ${{ env.SPRING_MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD: ${{ env.SPRING_MAIL_PASSWORD }}
          SERVER_SSL_KEY_STORE_PASSWORD: ${{ env.SERVER_SSL_KEY_STORE_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
          ENCRYPTION_KEY: ${{ env.ENCRYPTION_KEY }}


      - name: Log in to Docker Hub  # 登錄 Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker image  # 同時構建和推送 Docker 映像，減少步驟數量
        run: |
          docker build -t lunawewe/my-app:${{ github.sha }} .
          docker tag lunawewe/my-app:${{ github.sha }} lunawewe/my-app:latest
          docker push lunawewe/my-app:${{ github.sha }}
          docker push lunawewe/my-app:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy  # 部署到 EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 停止並刪除舊容器以節省資源，避免冗餘容器佔用
            RUNNING_CONTAINERS=$(sudo docker ps -q)
            if [ -n "$RUNNING_CONTAINERS" ]; then
              sudo docker stop $RUNNING_CONTAINERS
              sudo docker rm $RUNNING_CONTAINERS
            fi
            sudo docker system prune -a -f
            # 拉取最新映像，並通過環境變量設定來提供安全的數據庫及密鑰信息
            sudo docker pull lunawewe/my-app:latest
            # 使用卷掛載以保證密鑰文件的安全性
            sudo docker run -d -p 443:443 \
              -v /home/ec2-user/keystore.jks:/app/keystore.jks \
              -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }} \
              -e SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }} \
              -e SERVER_SSL_KEY_STORE_PASSWORD=${{ secrets.SERVER_SSL_KEY_STORE_PASSWORD }} \
              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }} \
              lunawewe/my-app:latest